name: mmlspark
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.1
  - numpy==1.15.4
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - matplotlib==2.2.2
  - pyspark==2.4.1
  - pip:
    - azure-cli==2.0.44
    - azureml-sdk[notebooks]==1.0.33
    - papermill==0.14.2
